def _items(topic: str, rows: list[tuple[str, str, str, str, str, str]]) -> list[dict[str, str]]:
    return [
        {
            "topic": topic,
            "phrase": phrase,
            "meaning_vi": meaning_vi,
            "example_sentence": example_sentence,
            "collocation": collocation,
            "writing_usage": writing_usage,
            "level": level,
        }
        for phrase, meaning_vi, example_sentence, collocation, writing_usage, level in rows
    ]


VOCABULARY_SEED = [
    *_items(
        "Education",
        [
            (
                "broaden one's horizons",
                "mở rộng tầm nhìn",
                "Studying abroad can broaden one's horizons and build independence.",
                "broaden one's horizons through education",
                "Dùng tốt khi nói về lợi ích của du học, đọc sách hoặc giáo dục.",
                "B2",
            ),
            (
                "acquire practical skills",
                "tiếp thu kỹ năng thực tế",
                "Students should acquire practical skills before entering the job market.",
                "acquire practical skills at school",
                "Dùng cho bài về mục tiêu của giáo dục hiện đại.",
                "B2",
            ),
            (
                "academic performance",
                "kết quả học tập",
                "Regular feedback can improve students' academic performance.",
                "improve academic performance",
                "Dùng khi nói về điểm số, học lực, áp lực học tập.",
                "B1",
            ),
            (
                "lifelong learning",
                "học tập suốt đời",
                "Lifelong learning is essential in a rapidly changing world.",
                "promote lifelong learning",
                "Phù hợp với essay về giáo dục người lớn và công nghệ.",
                "B2",
            ),
            (
                "critical thinking",
                "tư duy phản biện",
                "Schools should encourage critical thinking instead of rote learning.",
                "develop critical thinking",
                "Dùng để nâng cấp ý về kỹ năng học thuật.",
                "B2",
            ),
            (
                "rote learning",
                "học vẹt",
                "Rote learning may help students pass exams, but it limits creativity.",
                "rely on rote learning",
                "Dùng khi phê bình cách học chỉ ghi nhớ máy móc.",
                "B2",
            ),
            (
                "learning environment",
                "môi trường học tập",
                "A supportive learning environment helps students stay motivated.",
                "create a positive learning environment",
                "Dùng trong Task 2 về trường học, giáo viên, lớp học.",
                "B1",
            ),
            (
                "school curriculum",
                "chương trình học",
                "The school curriculum should include more life skills.",
                "update the school curriculum",
                "Dùng khi đề hỏi nên dạy môn gì ở trường.",
                "B1",
            ),
            (
                "student engagement",
                "sự tham gia của học sinh",
                "Interactive lessons can increase student engagement.",
                "increase student engagement",
                "Dùng cho chủ đề lớp học online, phương pháp giảng dạy.",
                "B2",
            ),
            (
                "equal access to education",
                "cơ hội tiếp cận giáo dục bình đẳng",
                "Governments should ensure equal access to education for children in rural areas.",
                "ensure equal access to education",
                "Dùng trong bài về bất bình đẳng, nông thôn, chính sách giáo dục.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Technology",
        [
            (
                "digital literacy",
                "khả năng sử dụng công nghệ số",
                "Digital literacy is now necessary for both students and workers.",
                "improve digital literacy",
                "Dùng khi nói về kỹ năng cần có trong xã hội hiện đại.",
                "B2",
            ),
            (
                "technological advancement",
                "sự tiến bộ công nghệ",
                "Technological advancement has changed the way people communicate.",
                "rapid technological advancement",
                "Dùng mở bài hoặc thân bài về tác động của công nghệ.",
                "B2",
            ),
            (
                "online learning platforms",
                "nền tảng học trực tuyến",
                "Online learning platforms allow learners to study at their own pace.",
                "use online learning platforms",
                "Dùng cho chủ đề học online và giáo dục từ xa.",
                "B1",
            ),
            (
                "data privacy",
                "quyền riêng tư dữ liệu",
                "Users should be aware of data privacy when using mobile apps.",
                "protect data privacy",
                "Dùng trong essay về mạng xã hội, app, AI, internet.",
                "B2",
            ),
            (
                "artificial intelligence",
                "trí tuệ nhân tạo",
                "Artificial intelligence can support teachers by giving instant feedback.",
                "apply artificial intelligence",
                "Dùng khi nói về AI trong giáo dục, công việc, y tế.",
                "B1",
            ),
            (
                "automation in the workplace",
                "tự động hóa trong nơi làm việc",
                "Automation in the workplace can increase productivity but reduce some jobs.",
                "adapt to automation in the workplace",
                "Dùng cho bài về việc làm và công nghệ.",
                "B2",
            ),
            (
                "screen time",
                "thời gian sử dụng màn hình",
                "Too much screen time can affect children's sleep and concentration.",
                "reduce screen time",
                "Dùng trong chủ đề trẻ em, sức khỏe, mạng xã hội.",
                "B1",
            ),
            (
                "access to information",
                "khả năng tiếp cận thông tin",
                "The internet gives people quick access to information.",
                "provide access to information",
                "Dùng khi nói về lợi ích của internet.",
                "B1",
            ),
            (
                "digital divide",
                "khoảng cách số",
                "The digital divide can make online education unfair for poor students.",
                "narrow the digital divide",
                "Dùng trong bài về bất bình đẳng công nghệ.",
                "B2",
            ),
            (
                "user-friendly design",
                "thiết kế dễ sử dụng",
                "A user-friendly design makes technology accessible to older people.",
                "create a user-friendly design",
                "Dùng cho chủ đề app, thiết bị, dịch vụ công nghệ.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Environment",
        [
            (
                "environmental pollution",
                "ô nhiễm môi trường",
                "Environmental pollution can seriously damage people's health.",
                "reduce environmental pollution",
                "Cụm cơ bản cho hầu hết bài môi trường.",
                "B1",
            ),
            (
                "climate change",
                "biến đổi khí hậu",
                "Climate change is one of the most serious global challenges.",
                "address climate change",
                "Dùng trong mở bài hoặc nêu vấn đề toàn cầu.",
                "B1",
            ),
            (
                "renewable energy",
                "năng lượng tái tạo",
                "Renewable energy can reduce dependence on fossil fuels.",
                "invest in renewable energy",
                "Dùng cho giải pháp môi trường và chính sách chính phủ.",
                "B2",
            ),
            (
                "carbon emissions",
                "lượng khí thải carbon",
                "Public transport can help reduce carbon emissions in big cities.",
                "cut carbon emissions",
                "Dùng khi nói về giao thông, công nghiệp, biến đổi khí hậu.",
                "B2",
            ),
            (
                "single-use plastic",
                "nhựa dùng một lần",
                "Single-use plastic should be limited to protect marine life.",
                "ban single-use plastic",
                "Dùng trong bài về rác thải và tiêu dùng.",
                "B2",
            ),
            (
                "sustainable lifestyle",
                "lối sống bền vững",
                "People can adopt a sustainable lifestyle by wasting less food.",
                "adopt a sustainable lifestyle",
                "Dùng cho giải pháp cá nhân trong essay môi trường.",
                "B2",
            ),
            (
                "waste management",
                "quản lý rác thải",
                "Better waste management is needed in crowded urban areas.",
                "improve waste management",
                "Dùng trong bài về thành phố, môi trường, chính sách.",
                "B2",
            ),
            (
                "protect natural habitats",
                "bảo vệ môi trường sống tự nhiên",
                "We need to protect natural habitats to save endangered animals.",
                "protect natural habitats from development",
                "Dùng khi đề liên quan đến động vật, rừng, đô thị hóa.",
                "B2",
            ),
            (
                "air quality",
                "chất lượng không khí",
                "Poor air quality can cause breathing problems.",
                "improve air quality",
                "Dùng trong chủ đề sức khỏe và thành phố.",
                "B1",
            ),
            (
                "raise environmental awareness",
                "nâng cao nhận thức về môi trường",
                "Schools can raise environmental awareness among young people.",
                "raise environmental awareness through education",
                "Dùng cho giải pháp giáo dục trong bài môi trường.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Health",
        [
            (
                "maintain a balanced diet",
                "duy trì chế độ ăn cân bằng",
                "People should maintain a balanced diet to stay healthy.",
                "maintain a balanced diet and exercise regularly",
                "Dùng cho bài về lối sống lành mạnh.",
                "B1",
            ),
            (
                "mental well-being",
                "sức khỏe tinh thần",
                "Regular exercise can improve mental well-being.",
                "support mental well-being",
                "Dùng khi nói về stress, học tập, công việc.",
                "B2",
            ),
            (
                "sedentary lifestyle",
                "lối sống ít vận động",
                "A sedentary lifestyle can increase the risk of obesity.",
                "avoid a sedentary lifestyle",
                "Dùng cho chủ đề công nghệ, sức khỏe, văn phòng.",
                "B2",
            ),
            (
                "public health",
                "sức khỏe cộng đồng",
                "Public health campaigns can encourage people to stop smoking.",
                "improve public health",
                "Dùng trong bài về vai trò chính phủ.",
                "B1",
            ),
            (
                "preventive healthcare",
                "chăm sóc sức khỏe phòng ngừa",
                "Preventive healthcare can reduce pressure on hospitals.",
                "invest in preventive healthcare",
                "Dùng khi đề hỏi cách giảm chi phí y tế.",
                "B2",
            ),
            (
                "healthy habits",
                "thói quen lành mạnh",
                "Children should develop healthy habits from an early age.",
                "develop healthy habits",
                "Dùng trong bài về gia đình, trường học, sức khỏe.",
                "B1",
            ),
            (
                "work-life balance",
                "cân bằng giữa công việc và cuộc sống",
                "A good work-life balance can reduce stress.",
                "achieve work-life balance",
                "Dùng cho chủ đề công việc và sức khỏe tinh thần.",
                "B2",
            ),
            (
                "healthcare services",
                "dịch vụ y tế",
                "Rural areas often have limited access to healthcare services.",
                "access healthcare services",
                "Dùng trong bài về nông thôn, chính phủ, bất bình đẳng.",
                "B1",
            ),
            (
                "physical fitness",
                "thể lực",
                "Sports help students improve physical fitness and teamwork.",
                "improve physical fitness",
                "Dùng khi nói về thể thao ở trường.",
                "B1",
            ),
            (
                "stress management",
                "quản lý căng thẳng",
                "Stress management is important for students before exams.",
                "learn stress management techniques",
                "Dùng cho chủ đề học tập, công việc, sức khỏe tinh thần.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Work",
        [
            (
                "career prospects",
                "triển vọng nghề nghiệp",
                "Learning English can improve young people's career prospects.",
                "improve career prospects",
                "Dùng cho chủ đề học tiếng Anh, đại học, việc làm.",
                "B2",
            ),
            (
                "job satisfaction",
                "sự hài lòng trong công việc",
                "Job satisfaction is important for long-term productivity.",
                "increase job satisfaction",
                "Dùng trong essay về lương, môi trường làm việc.",
                "B2",
            ),
            (
                "professional development",
                "phát triển nghề nghiệp",
                "Companies should provide professional development opportunities.",
                "support professional development",
                "Dùng khi nói về đào tạo nhân viên.",
                "B2",
            ),
            (
                "remote working",
                "làm việc từ xa",
                "Remote working gives employees more flexibility.",
                "allow remote working",
                "Dùng trong bài về work from home.",
                "B1",
            ),
            (
                "workplace productivity",
                "năng suất nơi làm việc",
                "Clear communication can improve workplace productivity.",
                "increase workplace productivity",
                "Dùng khi đề hỏi yếu tố giúp công ty hiệu quả hơn.",
                "B2",
            ),
            (
                "soft skills",
                "kỹ năng mềm",
                "Soft skills such as communication are valuable in most jobs.",
                "develop soft skills",
                "Dùng cho chủ đề giáo dục và việc làm.",
                "B1",
            ),
            (
                "competitive salary",
                "mức lương cạnh tranh",
                "A competitive salary can help companies attract talented workers.",
                "offer a competitive salary",
                "Dùng trong Task 1 application hoặc Task 2 về công việc.",
                "B2",
            ),
            (
                "heavy workload",
                "khối lượng công việc nặng",
                "A heavy workload can lead to stress and burnout.",
                "deal with a heavy workload",
                "Dùng khi nói về áp lực công việc.",
                "B1",
            ),
            (
                "team collaboration",
                "sự hợp tác nhóm",
                "Team collaboration is essential for complex projects.",
                "encourage team collaboration",
                "Dùng cho bài về kỹ năng làm việc và môi trường công sở.",
                "B2",
            ),
            (
                "job security",
                "sự ổn định công việc",
                "Many workers value job security more than a high salary.",
                "provide job security",
                "Dùng khi so sánh lương, ổn định, thăng tiến.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Travel",
        [
            (
                "experience different cultures",
                "trải nghiệm các nền văn hóa khác nhau",
                "Traveling allows people to experience different cultures.",
                "experience different cultures through travel",
                "Dùng trong bài về lợi ích của du lịch.",
                "B1",
            ),
            (
                "tourist attractions",
                "điểm tham quan du lịch",
                "Famous tourist attractions can bring income to local communities.",
                "visit tourist attractions",
                "Dùng trong Task 1 invitation hoặc essay về tourism.",
                "B1",
            ),
            (
                "local customs",
                "phong tục địa phương",
                "Visitors should respect local customs when traveling abroad.",
                "respect local customs",
                "Dùng trong bài về văn hóa và du lịch.",
                "B2",
            ),
            (
                "travel independently",
                "du lịch tự túc",
                "Young people often prefer to travel independently.",
                "travel independently instead of joining a tour",
                "Dùng khi so sánh du lịch theo tour và tự túc.",
                "B1",
            ),
            (
                "budget-friendly accommodation",
                "chỗ ở giá hợp lý",
                "Budget-friendly accommodation makes travel more accessible to students.",
                "book budget-friendly accommodation",
                "Dùng trong thư yêu cầu, email du lịch, hoặc essay travel.",
                "B2",
            ),
            (
                "boost the local economy",
                "thúc đẩy kinh tế địa phương",
                "Tourism can boost the local economy by creating jobs.",
                "boost the local economy through tourism",
                "Dùng cho lợi ích kinh tế của du lịch.",
                "B2",
            ),
            (
                "cultural exchange",
                "trao đổi văn hóa",
                "International travel encourages cultural exchange.",
                "promote cultural exchange",
                "Dùng trong bài về travel, education, culture.",
                "B2",
            ),
            (
                "overcrowded destinations",
                "điểm đến quá đông đúc",
                "Overcrowded destinations can make trips less enjoyable.",
                "avoid overcrowded destinations",
                "Dùng cho nhược điểm của du lịch đại chúng.",
                "B2",
            ),
            (
                "travel restrictions",
                "hạn chế đi lại",
                "Travel restrictions can affect tourism and business.",
                "lift travel restrictions",
                "Dùng trong chủ đề travel, health, economy.",
                "B2",
            ),
            (
                "memorable experience",
                "trải nghiệm đáng nhớ",
                "A trip with close friends can be a memorable experience.",
                "have a memorable experience",
                "Dùng trong Task 1 thank-you/invitation hoặc essay travel.",
                "B1",
            ),
        ],
    ),
    *_items(
        "Culture",
        [
            (
                "preserve cultural heritage",
                "bảo tồn di sản văn hóa",
                "Museums help preserve cultural heritage for future generations.",
                "preserve cultural heritage",
                "Dùng trong bài về bảo tàng, truyền thống, du lịch.",
                "B2",
            ),
            (
                "traditional values",
                "giá trị truyền thống",
                "Traditional values still play an important role in family life.",
                "respect traditional values",
                "Dùng cho chủ đề gia đình, văn hóa, xã hội hiện đại.",
                "B2",
            ),
            (
                "cultural identity",
                "bản sắc văn hóa",
                "Language is an important part of cultural identity.",
                "protect cultural identity",
                "Dùng khi nói về toàn cầu hóa và văn hóa.",
                "B2",
            ),
            (
                "global culture",
                "văn hóa toàn cầu",
                "Global culture influences the music and fashion young people enjoy.",
                "be influenced by global culture",
                "Dùng cho chủ đề globalisation, youth, media.",
                "B2",
            ),
            (
                "local traditions",
                "truyền thống địa phương",
                "Local traditions should be introduced to tourists in a respectful way.",
                "maintain local traditions",
                "Dùng trong bài về du lịch và văn hóa.",
                "B1",
            ),
            (
                "cultural diversity",
                "sự đa dạng văn hóa",
                "Cultural diversity can make communities more open-minded.",
                "celebrate cultural diversity",
                "Dùng trong chủ đề society, travel, education.",
                "B2",
            ),
            (
                "national pride",
                "lòng tự hào dân tộc",
                "Traditional festivals can strengthen national pride.",
                "strengthen national pride",
                "Dùng khi nói về lễ hội, truyền thống, di sản.",
                "B2",
            ),
            (
                "cultural event",
                "sự kiện văn hóa",
                "A cultural event is a good opportunity for visitors to learn about local life.",
                "attend a cultural event",
                "Dùng tốt trong Task 1 invitation letter.",
                "B1",
            ),
            (
                "modern lifestyle",
                "lối sống hiện đại",
                "A modern lifestyle can sometimes weaken family connections.",
                "adapt to a modern lifestyle",
                "Dùng trong bài về xã hội hiện đại.",
                "B1",
            ),
            (
                "language barrier",
                "rào cản ngôn ngữ",
                "The language barrier can make it difficult for tourists to communicate.",
                "overcome the language barrier",
                "Dùng trong chủ đề travel, culture, migration.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Family",
        [
            (
                "family bonds",
                "sự gắn kết gia đình",
                "Shared meals can strengthen family bonds.",
                "strengthen family bonds",
                "Dùng trong bài về gia đình và lối sống.",
                "B1",
            ),
            (
                "parental guidance",
                "sự hướng dẫn của cha mẹ",
                "Parental guidance helps children use the internet safely.",
                "provide parental guidance",
                "Dùng cho chủ đề trẻ em, giáo dục, công nghệ.",
                "B2",
            ),
            (
                "generation gap",
                "khoảng cách thế hệ",
                "The generation gap can lead to misunderstandings in families.",
                "bridge the generation gap",
                "Dùng khi nói về cha mẹ và con cái.",
                "B2",
            ),
            (
                "household responsibilities",
                "trách nhiệm trong gia đình",
                "Children should learn to share household responsibilities.",
                "share household responsibilities",
                "Dùng cho bài về giáo dục con cái và kỹ năng sống.",
                "B2",
            ),
            (
                "quality time",
                "thời gian chất lượng",
                "Parents should spend quality time with their children.",
                "spend quality time together",
                "Dùng trong chủ đề gia đình, công việc, sức khỏe tinh thần.",
                "B1",
            ),
            (
                "child development",
                "sự phát triển của trẻ",
                "Play is important for child development.",
                "support child development",
                "Dùng cho chủ đề trẻ em, giáo dục, thể thao.",
                "B2",
            ),
            (
                "financial pressure",
                "áp lực tài chính",
                "Financial pressure can make it difficult for parents to raise children.",
                "face financial pressure",
                "Dùng trong bài về gia đình, chi phí sống, công việc.",
                "B1",
            ),
            (
                "elderly care",
                "chăm sóc người cao tuổi",
                "Elderly care is becoming an important issue in many countries.",
                "provide elderly care",
                "Dùng khi đề nói về dân số già.",
                "B2",
            ),
            (
                "supportive family",
                "gia đình hỗ trợ",
                "A supportive family can help students deal with stress.",
                "have a supportive family",
                "Dùng trong bài về học tập, sức khỏe tinh thần.",
                "B1",
            ),
            (
                "work-family conflict",
                "xung đột giữa công việc và gia đình",
                "Work-family conflict can reduce parents' well-being.",
                "reduce work-family conflict",
                "Dùng cho chủ đề work-life balance.",
                "B2",
            ),
        ],
    ),
    *_items(
        "City life",
        [
            (
                "urban lifestyle",
                "lối sống thành thị",
                "The urban lifestyle is often fast-paced and stressful.",
                "adapt to an urban lifestyle",
                "Dùng trong bài về sống ở thành phố.",
                "B1",
            ),
            (
                "public transport",
                "giao thông công cộng",
                "Public transport can reduce traffic congestion.",
                "improve public transport",
                "Dùng cho bài về giao thông và thành phố.",
                "B1",
            ),
            (
                "traffic congestion",
                "tắc nghẽn giao thông",
                "Traffic congestion wastes time and increases air pollution.",
                "reduce traffic congestion",
                "Cụm quan trọng cho problem-solution essay.",
                "B1",
            ),
            (
                "cost of living",
                "chi phí sinh hoạt",
                "The cost of living in big cities is often very high.",
                "high cost of living",
                "Dùng trong bài so sánh thành phố và nông thôn.",
                "B1",
            ),
            (
                "housing shortage",
                "thiếu nhà ở",
                "A housing shortage can make rent unaffordable.",
                "deal with a housing shortage",
                "Dùng cho topic đô thị hóa, dân số, chính phủ.",
                "B2",
            ),
            (
                "green spaces",
                "không gian xanh",
                "Green spaces improve the quality of life in cities.",
                "create more green spaces",
                "Dùng trong giải pháp cải thiện thành phố.",
                "B1",
            ),
            (
                "urban planning",
                "quy hoạch đô thị",
                "Good urban planning can make cities more liveable.",
                "improve urban planning",
                "Dùng trong bài về city life và chính sách.",
                "B2",
            ),
            (
                "noise pollution",
                "ô nhiễm tiếng ồn",
                "Noise pollution can affect sleep and mental health.",
                "reduce noise pollution",
                "Dùng trong complaint letter hoặc essay về thành phố.",
                "B1",
            ),
            (
                "job opportunities",
                "cơ hội việc làm",
                "Big cities offer more job opportunities for young people.",
                "provide job opportunities",
                "Dùng khi nói về lý do người trẻ chuyển lên thành phố.",
                "B1",
            ),
            (
                "standard of living",
                "mức sống",
                "Better infrastructure can improve the standard of living.",
                "raise the standard of living",
                "Dùng trong bài về phát triển đô thị và kinh tế.",
                "B2",
            ),
        ],
    ),
    *_items(
        "Social media",
        [
            (
                "online communication",
                "giao tiếp trực tuyến",
                "Online communication helps people keep in touch across long distances.",
                "rely on online communication",
                "Dùng cho lợi ích của mạng xã hội và công nghệ.",
                "B1",
            ),
            (
                "social networking sites",
                "các trang mạng xã hội",
                "Social networking sites are popular among teenagers.",
                "use social networking sites",
                "Cụm cơ bản cho topic social media.",
                "B1",
            ),
            (
                "misleading information",
                "thông tin gây hiểu lầm",
                "Misleading information can spread quickly on social media.",
                "spread misleading information",
                "Dùng cho nhược điểm của mạng xã hội.",
                "B2",
            ),
            (
                "online reputation",
                "danh tiếng trực tuyến",
                "Young people should protect their online reputation.",
                "protect one's online reputation",
                "Dùng cho bài về hành vi trên mạng.",
                "B2",
            ),
            (
                "cyberbullying",
                "bắt nạt trên mạng",
                "Cyberbullying can seriously affect teenagers' mental health.",
                "prevent cyberbullying",
                "Dùng trong chủ đề trẻ em, mạng xã hội, sức khỏe.",
                "B2",
            ),
            (
                "digital footprint",
                "dấu vết số",
                "Every post can leave a digital footprint.",
                "manage one's digital footprint",
                "Dùng cho bài về quyền riêng tư và hành vi online.",
                "B2",
            ),
            (
                "content creation",
                "sáng tạo nội dung",
                "Content creation can help young people express their ideas.",
                "engage in content creation",
                "Dùng khi nói về lợi ích sáng tạo trên mạng.",
                "B2",
            ),
            (
                "social comparison",
                "sự so sánh xã hội",
                "Social comparison on social media may reduce self-confidence.",
                "avoid unhealthy social comparison",
                "Dùng cho tác động tiêu cực đến tâm lý.",
                "B2",
            ),
            (
                "online privacy",
                "quyền riêng tư trực tuyến",
                "Online privacy should be taught to children at school.",
                "protect online privacy",
                "Dùng trong bài về internet safety.",
                "B1",
            ),
            (
                "stay connected",
                "giữ kết nối",
                "Social media helps families stay connected when they live far apart.",
                "stay connected with friends and family",
                "Dùng khi nói về lợi ích giao tiếp của social media.",
                "B1",
            ),
        ],
    ),
]

